name: Code Quality and Testing on Staging

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        make install

    - name: Format code
      run: |
        make format

    - name: Lint with pylint
      run: |
        make lint

    - name: Test with pytest
      run: |
        make test

    - name: Clean up unnecessary files
      run: |
        make clean

    - name: Clean up virtual environment
      run: |
        make clean-venv